name: Glow Duck
favicon: null
layout_spectrum: 0.5035782002378255
typography_spectrum: 0.40206
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#fcb712'
    - '#d2d2d2'
    - '#6e6e6e'
    - '#b0b0b2'
  brandStrength: 0.3845147080719471
  lightness: 0.8045740083325654
  saturation: 0.4204812338575721
  rhythmicContrast: 0.31692767422646284
purpose: []
